#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Please run this as root."
  exit 1
fi

set -euxo pipefail

dnf upgrade -y

dnf remove -y snapshot gnome-contacts gnome-weather gnome-maps mediawriter libreoffice* totem gnome-calculator simple-scan gnome-boxes baobab gnome-connections evince gnome-abrt gnome-font-viewer gnome-logs rhythmbox gnome-tour gnome-system-monitor firefox gnome-software gnome-text-editor PackageKit PackageKit-glib ptyxis

dnf install -y adw-gtk3-theme rsms-inter-vf-fonts cascadia-code-nf-fonts wl-clipboard podman-compose stow htop btop fzf kitty

dnf install -y @development-tools cmake ninja-build android-tools

dnf install -y kubernetes-client helm opentofu

dnf install -y papers secrets flatseal fragments

dnf autoremove -y
