#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Please run this as root."
  exit 1
fi

set -euxo pipefail

dnf install -y gnome-shell gdm nautilus adw-gtk3-theme rsms-inter-vf-fonts \
  google-noto-fonts-all google-noto-color-emoji-fonts google-noto-emoji-fonts \
  btop flatpak

dnf install -y kitty neovim stow podman podman-compose systemd-container

dnf install -y npm golang @development-tools

systemctl enable gdm
systemctl set-default graphical.target

dnf autoremove -y
