#!/bin/bash

if [ "$EUID" -eq 0 ]; then
    echo "Please don't run this as root."
    exit 1
fi

set -euxo pipefail

mkdir -p $HOME/.local/bin
mkdir -p $HOME/.config/Code/User
mkdir -p $HOME/.var/app/com.dec05eba.gpu_screen_recorder/config/gtk-3.0
mkdir -p $HOME/.config/gtk-3.0
rm ~/.bashrc ~/.bash_profile

stow Home -t ~/

ln -s /usr/bin/kitty ~/.local/bin/gnome-terminal

git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0
. "$HOME/.asdf/asdf.sh"
asdf plugin add golang
asdf install golang latest
asdf global golang latest

asdf plugin add nodejs
asdf install nodejs latest
asdf global nodejs latest

flatpak remove --all -y

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak remote-modify flathub --enable

flatpak install -y flathub org.gtk.Gtk3theme.adw-gtk3 org.gtk.Gtk3theme.adw-gtk3-dark

flatpak install -y flathub org.gnome.Papers org.gnome.World.Secrets org.gnome.Loupe io.bassi.Amberol io.mpv.Mpv

flatpak install -y flathub com.github.wwmm.easyeffects com.dec05eba.gpu_screen_recorder \
	com.github.tchx84.Flatseal de.haeckerfelix.Fragments org.chromium.Chromium \
	md.obsidian.Obsidian com.mattjakeman.ExtensionManager

flatpak install -y flathub com.valvesoftware.Steam com.modrinth.ModrinthApp 
	 
# gnome

gsettings set org.gnome.shell.keybindings toggle-application-view []
gsettings set org.gnome.shell.keybindings toggle-overview []
gsettings set org.gnome.shell.keybindings toggle-quick-settings []
gsettings set org.gnome.shell.app-switcher current-workspace-only true

gsettings set org.gnome.mutter dynamic-workspaces false
gsettings set org.gnome.mutter center-new-windows true

gsettings set org.gnome.desktop.wm.preferences num-workspaces 6
gsettings set org.gnome.desktop.wm.preferences button-layout ":close"
gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "['<Shift><Super>f']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>a']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>s']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>d']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>f']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Super>c']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Super>x']"
gsettings set org.gnome.desktop.session idle-delay "uint32 0"
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
gsettings set org.gnome.desktop.interface clock-format '24h'

gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
gsettings set org.gnome.desktop.interface monospace-font-name 'Cascadia Code NF 13'
gsettings set org.gnome.desktop.interface font-name 'Inter Variable 11'
gsettings set org.gnome.desktop.interface document-font-name 'Inter Variable 11'
gsettings set org.gnome.desktop.interface accent-color 'slate'

gsettings set org.gnome.settings-daemon.plugins.power power-button-action 'interactive'
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding "<Super>Return"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command "kitty"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name "Terminal"

