#!/bin/bash

if [ "$EUID" -eq 0 ]; then
    echo "Please don't run this as root."
    exit 1
fi

set -euxo pipefail

# system
rpm-ostree override remove firefox firefox-langpacks gnome-software gnome-software-rpm-ostree ptyxis
rpm-ostree install rsms-inter-vf-fonts cascadia-code-nf-fonts adw-gtk3-theme kitty wl-clipboard stow distrobox podman-compose

# home
mkdir -p ~/.local/bin
rm -rf ~/.mozilla

ln -s /usr/bin/kitty ~/.local/bin/gnome-terminal

flatpak remove --all -y

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak remote-modify flathub --enable

flatpak install -y flathub org.gtk.Gtk3theme.adw-gtk3 org.gtk.Gtk3theme.adw-gtk3-dark

flatpak install -y flathub com.dec05eba.gpu_screen_recorder org.chromium.Chromium \
	com.mattjakeman.ExtensionManager io.mpv.Mpv io.bassi.Amberol org.gnome.clocks \
	org.gnome.Calendar org.gnome.Papers org.gnome.World.Secrets org.gnome.Loupe \
	com.github.tchx84.Flatseal de.haeckerfelix.Fragments 

flatpak install -y flathub com.valvesoftware.Steam com.modrinth.ModrinthApp \
    com.usebottles.bottles

# rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# asdf
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.1
. "$HOME/.asdf/asdf.sh"

asdf plugin add nodejs
asdf install nodejs latest
asdf global nodejs latest

# gnome
gsettings set org.gnome.shell.keybindings toggle-application-view []
gsettings set org.gnome.shell.keybindings toggle-overview []
gsettings set org.gnome.shell.keybindings toggle-quick-settings []
gsettings set org.gnome.shell.app-switcher current-workspace-only true

gsettings set org.gnome.mutter dynamic-workspaces false
gsettings set org.gnome.mutter center-new-windows true

gsettings set org.gnome.desktop.wm.preferences num-workspaces 4
gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "['<Shift><Super>f']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>a']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>s']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>d']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>f']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Super>c']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Super>x']"
gsettings set org.gnome.desktop.session idle-delay "uint32 0"
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
gsettings set org.gnome.desktop.interface clock-format '24h'
gsettings set org.gnome.settings-daemon.plugins.power power-button-action 'interactive'
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
